# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/FIR_filter/FIR_filter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter || ORIG_REF_NAME==FIR_filter} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_processing_system7_0_0/FIR_filter_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_processing_system7_0_0 || ORIG_REF_NAME==FIR_filter_processing_system7_0_0} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_fir_compiler_0_0/FIR_filter_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_fir_compiler_0_0 || ORIG_REF_NAME==FIR_filter_fir_compiler_0_0} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_axi_dma_0_0/FIR_filter_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_axi_dma_0_0 || ORIG_REF_NAME==FIR_filter_axi_dma_0_0} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_axi_smc_1/FIR_filter_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_axi_smc_1 || ORIG_REF_NAME==FIR_filter_axi_smc_1} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_rst_ps7_0_100M_1/FIR_filter_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_rst_ps7_0_100M_1 || ORIG_REF_NAME==FIR_filter_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_axi_mem_intercon_0/FIR_filter_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_axi_mem_intercon_0 || ORIG_REF_NAME==FIR_filter_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_axi_mem_intercon_imp_auto_pc_0/FIR_filter_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==FIR_filter_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/FIR_filter/ip/FIR_filter_axi_mem_intercon_imp_auto_us_0/FIR_filter_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIR_filter_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==FIR_filter_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/FIR_filter_ooc.xdc
