# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.srcs/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/FIR_filter_axi_smc_1.xci
# IP: The module: 'FIR_filter_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/bd_ac73.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_0/bd_ac73_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_1/bd_ac73_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_2/bd_ac73_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_3/bd_ac73_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_4/bd_ac73_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_5/bd_ac73_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_6/bd_ac73_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_7/bd_ac73_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_8/bd_ac73_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_9/bd_ac73_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_10/bd_ac73_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_11/bd_ac73_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_12/bd_ac73_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_1/bd_ac73_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_1/bd_ac73_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_5/bd_ac73_s00a2s_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_6/bd_ac73_sarn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_7/bd_ac73_srn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_8/bd_ac73_sawn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_9/bd_ac73_swn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_10/bd_ac73_sbn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_11/bd_ac73_m00s2a_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_filter_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_filter_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.srcs/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/FIR_filter_axi_smc_1.xci
# IP: The module: 'FIR_filter_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/bd_ac73.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_0/bd_ac73_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_1/bd_ac73_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_2/bd_ac73_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_3/bd_ac73_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_4/bd_ac73_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_5/bd_ac73_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_6/bd_ac73_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_7/bd_ac73_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_8/bd_ac73_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_9/bd_ac73_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_10/bd_ac73_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_11/bd_ac73_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_12/bd_ac73_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_1/bd_ac73_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_1/bd_ac73_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_5/bd_ac73_s00a2s_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_6/bd_ac73_sarn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_7/bd_ac73_srn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_8/bd_ac73_sawn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_9/bd_ac73_swn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_10/bd_ac73_sbn_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/bd_0/ip/ip_11/bd_ac73_m00s2a_0_ooc.xdc

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_filter_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repositories/PYNQ-Z2/FIR_filter/FIR_filter.gen/sources_1/bd/FIR_filter/ip/FIR_filter_axi_smc_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_filter_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
